CREATE TABLE Category(
    id int primary key generated by default as identity ,
    category_name varchar(32) unique not null
);

CREATE TABLE Delivery_Way
(
    id int primary key generated by default as identity ,
    way varchar(32) unique not null
);

CREATE TABLE Status(
    id int primary key generated by default as identity ,
    status_name varchar(32) unique not null
);

CREATE TABLE Promo_Code
(
    id int primary key generated by default as identity ,
    code char(10) unique not null
);

CREATE TABLE Payment_Way
(
    id int primary key generated by default as identity ,
    way varchar(32) unique not null
);

CREATE TABLE User_Role
(
    id int primary key generated by default as identity ,
    user_role varchar(32) unique not null
);
CREATE TABLE Item(
    id int primary key generated by default as identity ,
    item_name varchar(64),
    price int not null,
    description text not null,
    prep_time int not null,
    category_id int references Category(id)
);

CREATE TABLE Order_Item(
    id int primary key generated by default as identity ,
    count int not null ,
    prep_time int not null,
    item_id int references Item(id)
);

CREATE TABLE "user"(
    id int primary key generated by default as identity ,
    user_name varchar(32) not null,
    surname varchar(32) not null,
    phone varchar(16) not null unique ,
    email varchar(64) not null unique ,
    username varchar(32) not null unique ,
    user_password varchar(32) check ( length(user_password) > 7 ),
    user_role_id int references User_Role (id) not null
);

CREATE TABLE Restaurant(
    id int primary key generated by default as identity ,
    admin_id int references "user"(id) not null unique ,
    address varchar(64) not null unique ,
    longitude numeric not null,
    latitude numeric not null
);

CREATE TABLE "order"(
    id int primary key generated by default as identity ,
    prep_time int not null ,
    wish text,
    restaurant_id int references Restaurant(id),
    payment_way_id int references Payment_Way (id),
    promo_code_id int references Promo_Code(id),
    status_id int references Status(id),
    delivery_way_id int references Delivery_Way(id),
    order_item_id int references Order_Item(id)
);

ALTER TABLE "user" ADD COLUMN restaurant_id int references Restaurant(id) unique;